#!/usr/bin/env python3
"""Generate a progress snapshot and commit+push to git.

Designed to run via cron. Produces a lightweight STATUS.md that
tracks backfill progress without committing large data files.
"""

import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from riverwriter import config
from riverwriter.catalog import Catalog


def generate_status() -> dict:
    """Build a status snapshot from the catalog."""
    catalog = Catalog()
    summary = catalog.summary()

    parquet_mb = 0.0
    if config.PARQUET_DIR.exists():
        parquet_mb = sum(
            f.stat().st_size for f in config.PARQUET_DIR.rglob("*.parquet")
        ) / (1024 * 1024)

    raw_mb = 0.0
    if config.RAW_DIR.exists():
        raw_mb = sum(
            f.stat().st_size for f in config.RAW_DIR.rglob("*.bi5")
        ) / (1024 * 1024)

    total_fetched = sum(s.get("fetched", 0) for s in summary.values())
    total_no_data = sum(s.get("no_data", 0) for s in summary.values())
    total_errors = sum(s.get("error", 0) for s in summary.values())
    total_slots = sum(s.get("total", 0) for s in summary.values())

    return {
        "updated_at": datetime.now(timezone.utc),
        "totals": {
            "slots_processed": total_slots,
            "fetched": total_fetched,
            "no_data": total_no_data,
            "errors": total_errors,
            "parquet_mb": round(parquet_mb, 1),
            "raw_bi5_mb": round(raw_mb, 1),
        },
        "pairs": {
            pair: {
                "oldest": s.get("oldest"),
                "newest": s.get("newest"),
                "fetched": s.get("fetched", 0),
                "no_data": s.get("no_data", 0),
                "errors": s.get("error", 0),
            }
            for pair, s in summary.items()
        },
    }


def render_markdown(status: dict) -> str:
    """Render status dict as a markdown document."""
    t = status["totals"]
    ts = status["updated_at"].strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# RiverWriter Backfill Status",
        "",
        f"*Last updated: {ts}*",
        "",
        "## Totals",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Slots processed | {t['slots_processed']:,} |",
        f"| Hours with data | {t['fetched']:,} |",
        f"| No data (weekends/holidays) | {t['no_data']:,} |",
        f"| Errors | {t['errors']:,} |",
        f"| Parquet size | {t['parquet_mb']:.1f} MB |",
        f"| Raw .bi5 size | {t['raw_bi5_mb']:.1f} MB |",
        "",
        "## Per Pair",
        "",
        "| Pair | Oldest | Newest | Fetched | No Data | Errors |",
        "|------|--------|--------|--------:|--------:|-------:|",
    ]

    for pair, s in status["pairs"].items():
        oldest = s["oldest"] or "--"
        newest = s["newest"] or "--"
        lines.append(
            f"| {pair} | {oldest} | {newest} | "
            f"{s['fetched']:,} | {s['no_data']:,} | {s['errors']:,} |"
        )

    lines.extend(["", "---", "*Auto-generated by `report_progress.py`*", ""])
    return "\n".join(lines)


def main():
    repo = Path(__file__).resolve().parent
    status = generate_status()

    # Write STATUS.md
    status_path = repo / "STATUS.md"
    status_path.write_text(render_markdown(status))

    # Build a commit message
    t = status["totals"]
    msg = (
        f"progress: {t['fetched']:,} hrs fetched | "
        f"{t['slots_processed']:,} slots | "
        f"{t['parquet_mb']:.1f} MB"
    )

    # Git add, commit, push
    try:
        subprocess.run(["git", "add", "STATUS.md"], cwd=repo, check=True, capture_output=True)
        result = subprocess.run(
            ["git", "diff", "--cached", "--quiet"], cwd=repo, capture_output=True
        )
        if result.returncode == 0:
            print("No changes to commit")
            return

        subprocess.run(
            ["git", "commit", "-m", msg],
            cwd=repo, check=True, capture_output=True,
        )
        subprocess.run(
            ["git", "push"],
            cwd=repo, check=True, capture_output=True, timeout=30,
        )
        print(f"Pushed: {msg}")
    except subprocess.CalledProcessError as e:
        print(f"Git error: {e.stderr.decode() if e.stderr else e}", file=sys.stderr)
        sys.exit(1)
    except subprocess.TimeoutExpired:
        print("Push timed out", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
